### ISSUE TITLE
Description of Color, as well as variable names seems to mismatch reality

### ISSUE THREAD

**Issue by LuPro** [Metalab/dramabar#3]
I'm not entirely sure, but I think, that the order of the colors in the function "Color" are mixed up:

```
// Create a 24 bit color value from R,G,B
uint32_t Color(byte r, byte g, byte b)
{
  uint32_t c;
  c = r;
  c <<= 8;
  c |= g;
  c <<= 8;
  c |= b;
  return c;
}
```

based on the functions resetGreen and resetRed:

```
void resetGreen()
{
  for (int i = 0; i < strip.numPixels(); i++) {
    strip.setPixelColor(i, Color(255, 0, 0));
  }
  strip.show();   // write all the pixels out

}
```

the correct order seems to be G-R-B.

Not putting it in a pull request, since I'm not sure and it only affects the code commentary

**Comment by wizard23** [comment]
Chinese LEDs always come with mixed up color channels. I've literally seen every combination (there are not many). If you have seen it with your own eyes that a "Green" command leads to a "Red" state then you are probably right about the specific setup at Metalab. To improve the code an make it reusable just add functionality to easily configure the color coding and set the defaults for the specific Metalab environment to GRB :)

thanks for taking the time to look at the thing!

**Comment by LuPro** [comment]
Well I haven't specifically tested it, but the code doesn't make any sense in several functions if the order isn't GRB. And since I see the dramabar live in the lab and I see that it works correctly I am pretty confident regarding the order
EDIT: It is now fixed in my pull request for the code update
